Repository TeamCherish/Cherish-iOS, pull requests merged in 2021-12, with the labels that each got.

#40 [#39] About Cherish에 Cherish 공식 인스타 계정 버튼 추가
  Cherish-iOS/Cherish-iOS/Screens/Onboarding/Storyboards/Onboarding.storyboard
  Cherish-iOS/Cherish-iOS/Screens/ShowMore/Controllers/AboutCherishVC.swift
  Cherish-iOS/Cherish-iOS/Screens/ShowMore/Storyboards/ShowMore.storyboard
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/btnCherishInstagram.imageset/Contents.json
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/btnCherishInstagram.imageset/btnCherishInstagram.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/btnCherishInstagram.imageset/btnCherishInstagram@2x.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/btnCherishInstagram.imageset/btnCherishInstagram@3x.png
Labels: feat :)

#42 [#41] 비밀번호 설정 및 검사 로직 리팩토링, 개인정보 보호 뷰 추가
  Cherish-iOS/Cherish-iOS.xcodeproj/project.pbxproj
  Cherish-iOS/Cherish-iOS/Global/Class/CircularProgressBar.swift
  Cherish-iOS/Cherish-iOS/Global/Class/CircularProgressView.swift
  Cherish-iOS/Cherish-iOS/Global/Class/CollectionViewAlign.swift
  Cherish-iOS/Cherish-iOS/Global/Class/CustomPageControl.swift
  Cherish-iOS/Cherish-iOS/Global/Class/CustomSegmentedControl.swift
  Cherish-iOS/Cherish-iOS/Global/Extension/UIButton+Extention.swift
  Cherish-iOS/Cherish-iOS/Global/Extension/UIColor+Additions.swift
  Cherish-iOS/Cherish-iOS/Global/Extension/UILabel+.swift
  Cherish-iOS/Cherish-iOS/Global/UIComponents/BackNaviView.swift
  Cherish-iOS/Cherish-iOS/Global/UIComponents/CherishBtn.swift
  Cherish-iOS/Cherish-iOS/Global/UIComponents/CherishTextField.swift
  Cherish-iOS/Cherish-iOS/Screens/AddUser/Controllers/SelectFriendSearchBar.swift
  Cherish-iOS/Cherish-iOS/Screens/Calendar/Controllers/CalendarVC.swift
  Cherish-iOS/Cherish-iOS/Screens/Calendar/Controllers/ReviewEditVC.swift
  Cherish-iOS/Cherish-iOS/Screens/MyPage/Controllers/MyPageSearchContactVC.swift
  Cherish-iOS/Cherish-iOS/Screens/MyPage/Controllers/MyPageSearchPlantVC.swift
  Cherish-iOS/Cherish-iOS/Screens/MyPage/Controllers/MyPageSearchVC.swift
  Cherish-iOS/Cherish-iOS/Screens/MyPage/Controllers/MyPageVC.swift
  Cherish-iOS/Cherish-iOS/Screens/PlantDetail/Controllers/PlantDetailVC.swift
  Cherish-iOS/Cherish-iOS/Screens/ShowMore/Controllers/PrivateComponent/BlurryView.swift
  Cherish-iOS/Cherish-iOS/Screens/ShowMore/Controllers/PrivateComponent/LeafModel.swift
  Cherish-iOS/Cherish-iOS/Screens/ShowMore/Controllers/SetLockVC.swift
  Cherish-iOS/Cherish-iOS/Screens/SignUp/Controllers/SignUpAccountVC.swift
  Cherish-iOS/Cherish-iOS/Screens/SignUp/Controllers/SignUpNicknameVC.swift
  Cherish-iOS/Cherish-iOS/Screens/SignUp/Controllers/SignUpPhoneVC.swift
  Cherish-iOS/Cherish-iOS/Screens/TabBar/Controllers/CherishTabBarController.swift
  Cherish-iOS/Cherish-iOS/Screens/Watering/Cells/KeywordCVC.swift
  Cherish-iOS/Cherish-iOS/Screens/Watering/Controllers/PopUpLaterVC.swift
  Cherish-iOS/Cherish-iOS/Screens/Watering/Controllers/ReviewVC.swift
  Cherish-iOS/Cherish-iOS/Supports/SceneDelegate.swift
Labels: refactor :p

#45 💄[MOD] : 크리스마스(겨울버전) appIcon 변경
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/1024.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/120-1.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/120.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/180.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/40.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/58.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/60.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/80.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/87.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/Contents.json
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/Icon-1024 real.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/Icon-121.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/Icon-58.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/Icon-80.png
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/AppIcon.appiconset/Icon-87.png
Labels: feat :)

#46 [Feat/#43] 메인뷰 눈내리는 기능 구현⚡️
  Cherish-iOS/Cherish-iOS/Screens/CherishMain/Controllers/MainContentVC.swift
  Cherish-iOS/Cherish-iOS/Screens/CherishMain/Storyboards/CherishMain.storyboard
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/snowball.imageset/Contents.json
  Cherish-iOS/Cherish-iOS/Supports/Assets.xcassets/snowball.imageset/snowball.png
Labels: feat :)

#48 [Hotfix/#47] 식물추가뷰 잘못나오는 버그 수정을 위한 로직 변경
  Cherish-iOS/Cherish-iOS.xcodeproj/project.pbxproj
  Cherish-iOS/Cherish-iOS/Global/AppModels/Main/MainSelectedData.swift
  Cherish-iOS/Cherish-iOS/Global/AppModels/Main/isCherishDataChanged.swift
  Cherish-iOS/Cherish-iOS/Screens/AddUser/Controllers/AddUserVC.swift
  Cherish-iOS/Cherish-iOS/Screens/AddUser/Controllers/PlantResultVC.swift
  Cherish-iOS/Cherish-iOS/Screens/CherishMain/Controllers/DetailContentVC.swift
  Cherish-iOS/Cherish-iOS/Screens/PlantDetail/Controllers/PlantEditVC.swift
  Cherish-iOS/Cherish-iOS/Supports/AppDelegate.swift
  Cherish-iOS/Cherish-iOS/Supports/SceneDelegate.swift
Labels: fix :0
