Repository TeamCherish/Cherish-iOS, pull requests merged in 2021-08, with the labels that each got.

#17 Feat/#15 PlantDetailPopUpVC에서 횡 스크롤 애니메이션 끊기는 현상 수정완료
  Cherish-iOS/Cherish-iOS/Resources/Storyboard/PlantDetail.storyboard
  Cherish-iOS/Cherish-iOS/Sources/ VC/PlantDetail/PlantDetailPopUpExplainVC.swift
Labels: bug :(, fix :0

#18 [Style] 식물카드뷰 label 더미 삭제
  Cherish-iOS/Cherish-iOS/Resources/Storyboard/PlantDetail.storyboard
Labels: fix :0

#16 [Feat] Release 1.0 reject 사유 반영하여 수정
  Cherish-iOS/Cherish-iOS/Info.plist
  Cherish-iOS/Cherish-iOS/Resources/Storyboard/CherishMain.storyboard
  Cherish-iOS/Cherish-iOS/Sources/ VC/CherishMain/DetailContentVC.swift
Labels: fix :0

#20 [refactor] 식물 상세 뷰 팝업 카드 부분 Kingfisher 적용
  Cherish-iOS/Cherish-iOS/Sources/ VC/PlantDetail/PlantDetailPopUpExplainVC.swift
Labels: refactor :p

#24 [Feat/#23] 연락처 0개일 때 처리 & iPhone8 탭바 사이즈 조정 & myPageView scroll시 statusbar size error 해결
  Cherish-iOS/Cherish-iOS/Resources/Storyboard/AddUser.storyboard
  Cherish-iOS/Cherish-iOS/Resources/Storyboard/MyPage.storyboard
  Cherish-iOS/Cherish-iOS/Resources/Storyboard/PlantDetail.storyboard
  Cherish-iOS/Cherish-iOS/Resources/Storyboard/Watering/PopUpContact.storyboard
  Cherish-iOS/Cherish-iOS/Sources/ VC/AddUser/SelectFriendSearchBar.swift
  Cherish-iOS/Cherish-iOS/Sources/ VC/Login/LoginVC.swift
  Cherish-iOS/Cherish-iOS/Sources/ VC/MyPage/MyPageVC.swift
  Cherish-iOS/Cherish-iOS/Sources/ VC/MyPage/MypageContactVC.swift
  Cherish-iOS/Cherish-iOS/Sources/ VC/TabBar/CherishTabBarController.swift
Labels: bug :(, feat :), fix :0

#27 [Feat/#26] Info.plist 연락처 동의멘트 수정
  Cherish-iOS/Cherish-iOS.xcodeproj/project.pbxproj
  Cherish-iOS/Cherish-iOS/Info.plist
Labels: refactor :p, fix :0
